[package]
name = "nvinfo_rs"
version = "0.1.0"
authors = ["ikr7 <kunpei.ikuta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
